### ISSUE TITLE
Error still displayed

### ISSUE THREAD

**Issue by Gounlaf** [DavidHavl/DhErrorLogging#11]
Hi,

I just installed and use the "default configuration" (no email sending, and just the default stream logger) ;
the module is enable "first"

*Error:* my database server is shutdown, so I got a PDO Exception
*Result:* the default HTML page you provide is well displayed, but the error is still echo in source ;
The web browser doesn't display it, but the error is still accessible for anyone ;

Does I missed something ?

Notes: 
- When `display_errors` is set to `Off` it works well, but I thank your module allow this settings to be set `On` or `Off` according to [buffer clean](https://github.com/DavidHavl/DhErrorLogging/blob/master/Module.php#L126) in Module.php

~~~html
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host &quot;localhost&quot; and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host &quot;localhost&quot; and accepting
	TCP/IP connections on port 5432?' in /foo/bar/zf2-skeleton/vendor/bshaffer/oauth2-server-php/src/OAuth2/Storage/Pdo.php:53
Stack trace:
#0 /foo/bar/zf2-skeleton/vendor/bshaffer/oauth2-server-php/src/OAuth2/Storage/Pdo.php(53): PDO-&gt;__construct('pgsql:dbname=ja...', 'florianlevis', NULL, Array)
#1 /foo/bar/zf2-skeleton/vendor/zfcampus/zf-oauth2/src/Adapter/PdoAdapter.php(89): OAuth2\Storage\Pdo-&gt;__construct(Array, Array)
#2 /foo/bar/zf2-skeleton/vendor/zfcampus/zf-oauth2/src/Factory/PdoAdapterFactory.php(45): ZF\OAuth2\Adapter\PdoAdapter-&gt;__construct(Array, Array)
#3 [internal function]: ZF\OA in <b>/foo/bar/zf2-skeleton/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php</b> on line <b>930</b><br />
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <title>We're sorry!</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style type="text/css">
        *
        {
            color: white;
            font-family: Helvetica, arial, sans-serif;
            margin: 0px;
~~~

Thanks,

Regards

**Comment by DavidHavl** [comment]
Hi @Gounlaf.
If you have `display_errors` set to `on` there is no way to prevent showing the error as it went out to STDOUT already before shutdown function intercepted. The `buffer clean` does not help unfortunately.

**Comment by Gounlaf** [comment]
Hi @DavidHavl,

Thanks for the answer, I didn't know that.
I have another question but I will create a new issue =)

Thanks

**Comment by DavidHavl** [comment]
Feel free to email me if it is not an error or issue.
