### ISSUE TITLE
Careful with new releases

### ISSUE THREAD

**Issue by teseo** [DavidHavl/DhErrorLogging#12]
Hello,

Few minutes ago you updated master and happened to break my whole application. 

The error I got was:
```php
PHP Fatal error:  Uncaught exception 'Zend\Stdlib\Exception\BadMethodCallException' with message 'The option "priority" does not have a matching "setPriority" ("setpriority") setter method which must be defined' in /repo/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php:110
Stack trace:
#0 /repo/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php(62): Zend\Stdlib\AbstractOptions->__set('priority', 6)
#1 /repo/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php(32): Zend\Stdlib\AbstractOptions->setFromArray(Array)
#2 /repo/vendor/davidhavl/dherrorlogging/src/DhErrorLogging/Options/Factory/ModuleOptionsFactory.php(21): Zend\Stdlib\AbstractOptions->__construct(Array)
#3 [internal function]: DhErrorLogging\Options\Factory\ModuleOptionsFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'dherrorloggingo...', 'DhErrorLogging\\...')
#4 /repo/vendor/liquid-cr in /repo/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 930

Fatal error: Uncaught exception 'Zend\Stdlib\Exception\BadMethodCallException' with message 'The option "priority" does not have a matching "setPriority" ("setpriority") setter method which must be defined' in /repo/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php:110
Stack trace:
#0 /repo/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php(62): Zend\Stdlib\AbstractOptions->__set('priority', 6)
#1 /repo/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php(32): Zend\Stdlib\AbstractOptions->setFromArray(Array)
#2 /repo/vendor/davidhavl/dherrorlogging/src/DhErrorLogging/Options/Factory/ModuleOptionsFactory.php(21): Zend\Stdlib\AbstractOptions->__construct(Array)
#3 [internal function]: DhErrorLogging\Options\Factory\ModuleOptionsFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'dherrorloggingo...', 'DhErrorLogging\\...')
#4 /repo/vendor/ in /repo/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 930
```

Many thanks for your work!

**Comment by teseo** [comment]
I was using dev-master in composer.json . I have a custom writer and i'm going to stick to v1.0.

What's new in this version?

**Comment by DavidHavl** [comment]
Hi Teseo,
The version 2 is still in alpha stage, but nearly ready.
It is a BIG change and has a lot improvement from v1. 

Some points:

- content negotiation (html/json), 
- handles CLI, 
- now also handles pre MVC errors and exceptions (for example those in bootstrap method of modules)
- you can choose which errors/exceptions will be logged
- there is a new exception filter
- there is proper module options functionality
- and also has dedicated response sender (which can be overwritten by anyone if desired)
 
The above error is because now there is no "priority" setting any more. Maybe I should gracefully handle any extra settings.

Let me know if you have any questions.

**Comment by andrewdrake** [comment]
Does this now require PHP5.5+?
Parse error: syntax error, unexpected '[' in ..... /davidhavl/dherrorlogging/src/DhErrorLogging/Options/Factory/ModuleOptionsFactory.php on line 21

**Comment by DavidHavl** [comment]
@andrewdrake 
A good point, thanks.
You are right function array dereferencing works only from 5.4. I have adjusted it to still support php 5.3 now.

@teseo 
The leftover priority option now does not create problems any more.

**Comment by andrewdrake** [comment]
Cool, yeah I'm still on PHP5.3 in production as I'm sure many still are. A reminder though I need to look at upgrade planning soon!
