### ISSUE TITLE
class map in module having issues

### ISSUE THREAD

**Issue by teseo** [DavidHavl/DhErrorLogging#13]
I spent some time this morning upgrading to the latest version and I've noticed that the location of Logger in the last release is in a different place.

It used to be 'DhErrorLogging\Factory\Logger\LoggerFactory' and right now is 'DhErrorLogging\Logger\Factory\LoggerFactory' I had to regenerate the class map and change dherrorloging.global.php with this changes.

I wonder wether this is the way to go or a potential bug.

**Comment by DavidHavl** [comment]
Yes the factories are now in more correct location (in my opinion). I think having them as a subfolder of objects they belong to makes more sense.
So this is the way to go.
