### ISSUE TITLE
Custom view templates overwritten

### ISSUE THREAD

**Issue by seaneble** [DavidHavl/DhErrorLogging#16]
Hello David,

I have set up quite nice error pages for my ZF2 application (in ```module/Application/view/error/…```). As soon as I activate your module (with appropriate configuration), Zend always uses the view files your module provides (```vendor/davidhavl/dherrorlogging/view/error/…```).

Do you know why? The order of the modules seems to have no effect.

Sebastian

**Comment by DavidHavl** [comment]
Hi Sebastian,

In V2 this is set as default because there are few different templates for different types of errors/exceptions.
To enable your own error template you can simply change a path of the template you want to override in dherrorlogging.global.php file in the 'templates' section:

```
'templates' => array(
         // error during dispatch lifecycle. comment out if you want to use the default zend skeleton one.
         'dispatch' => __DIR__ . '/../view/error/dispatch.phtml',
         // error during render lifecycle. comment out if you want to use the default zend skeleton one.
         'render' => __DIR__ . '/../view/error/render.phtml',
         // exceptions outside of mvc (i.e. while in module bootstrap,..)
         'exception' => __DIR__ . '/../view/error/exception.html',
         // native errors while outside of mvc (i.e. while in module bootstrap,..)
         'error' => __DIR__ . '/../view/error/error.html',
         // fatal errors while outside of mvc (i.e. while in module bootstrap,..)
         'fatal' => __DIR__ . '/../view/error/fatal.html',
         // error output while in CLI
         'console' => __DIR__ . '/../view/error/console.txt',
         // error output when json response requested
         'json' => __DIR__ . '/../view/error/json.js'
    ),
```

Let me know if this helps.

**Comment by seaneble** [comment]
Thanks for your time, I will try that. Though it already sounds familiar, somehow…

**Comment by seaneble** [comment]
Works perfectly. Thanks again!

**Comment by DavidHavl** [comment]
That is great. Let me know if you need more help or find bugs.
