### ISSUE TITLE
More detailed requirements

### ISSUE THREAD

**Issue by seaneble** [DavidHavl/DhErrorLogging#17]
I'm currently optimizing my composer.json. The major change is that I don't require ```zendframework/zendframework``` anymore, but only those components that I actually use (MVC, View, Session, I18n).

Unfortunately, that leads to a conflict with your composer.json, which would like to install the whole framework. But is that really necessary? Do you depend on all components?

**Comment by DavidHavl** [comment]
Yes that is a valid concern at this point. Thanks, I will work on it.

**Comment by seaneble** [comment]
Perfect, thanks!

**Comment by DavidHavl** [comment]
This should do the trick.
I will be tagging the current set of code as new version 2.0 . I think it is about time.

Any other issues you came across before I do that?

**Comment by seaneble** [comment]
Actually, your component works pretty well all the time and I can't recall any issues we would have had. Thanks for the great work!

**Comment by DavidHavl** [comment]
Awesome. Thanks.
