### ISSUE TITLE
Is it compatible for Zend 3?

### ISSUE THREAD

**Issue by jmj4you** [DavidHavl/DhErrorLogging#19]
I tried for ZF3, following error shows.

Fatal error: Class DhErrorLogging\Options\Factory\ModuleOptionsFactory contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zend\ServiceManager\Factory\FactoryInterface::__invoke) in /var/www/html/zf3-skelton/vendor/davidhavl/dherrorlogging/src/DhErrorLogging/Options/Factory/ModuleOptionsFactory.php on line 23

**Comment by DavidHavl** [comment]
Hello jmj4you,
the module is now ready for ZF3.

**Comment by jmj4you** [comment]
Thank you very much.
