### ISSUE TITLE
ZF3 ZendDB logging issue: zend_db_adapter does not have a callable setZendDbAdapter

### ISSUE THREAD

**Issue by CraigDSmith** [DavidHavl/DhErrorLogging#22]
Hi David

I have been using your logging module successfully with ZF2 logging to the database with Zend DB.

I am now trying to use this with ZF3 and getting the following error:

```
PHP Fatal error:  Uncaught exception 'Zend\Stdlib\Exception\BadMethodCallException' with message 'The option "zend_db_adapter" does not have a callable "setZendDbAdapter" ("setzenddbadapter") setter method which must be defined' in /vendor/zendframework/zend-stdlib/src/AbstractOptions.php:112
Stack trace:
#0 /vendor/zendframework/zend-stdlib/src/AbstractOptions.php(64): Zend\Stdlib\AbstractOptions->__set('zend_db_adapter', 'Zend\\Db\\Adapter...')
#1 /vendor/zendframework/zend-stdlib/src/AbstractOptions.php(34): Zend\Stdlib\AbstractOptions->setFromArray(Array)
#2 /vendor/davidhavl/dherrorlogging/src/DhErrorLogging/Options/Factory/ModuleOptionsFactory.php(24): Zend\Stdlib\AbstractOptions->__construct(Array)
#3 /vendor/zendframework/zend-servicemanager/src/ServiceManager.php(758): DhErrorLogging\Options\Facto in /vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 765
```

Some googling found that another project had this problem, and they fixed it by adding 

`$__strictmode__ = false;`

to the Options/ModuleOptions.php

[https://github.com/SocalNick/ScnSocialAuth/commit/7d153b15cf10bc8de9302ae7d10b7ef8e1f95038](https://github.com/SocalNick/ScnSocialAuth/commit/7d153b15cf10bc8de9302ae7d10b7ef8e1f95038)

I've tested this and it works with this module, but seems like a bit of a hack to me.

**Comment by DavidHavl** [comment]
Hi Craig,
Sorry for the late reply.
Basically the 
You can fix this by just deleting the 
`'zend_db_adapter' => 'Zend\Db\Adapter\Adapter'`
line near end of the config file (around line 184) and just set that value (if different from the specified) to the alias 'dherrorlogging_zend_db_adapter' (line 200) instead.
If you have a look at the current config file (config/dherrorlogging.global.php.dist) you can see what I mean. It was basically duplicated for no big reason, so I have removed it now from the current version and left only the alias on bottom.

I have also released fix for it anyway in case you just wanna leave your config the way it is and just update the package.
Hope it helped.
